export { default as Login } from './login'
export { default as Join } from './join'
export { default as PostList } from './postlist'
export { default as Sidebar } from './sidebar'
export { default as SPOST } from './postinfo'
export { default as profile } from './profile'
export { default as Post } from './post'
export { default as UPOST } from './postmodify'